version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db

  cache:
    container_name: redis_cache
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  # Node API service
  api:
    container_name: node_server
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: test_db
      NAME: TrulyMittal
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
  cache:
    driver: local
